---
title: "pre-processing_code"
output: html_document
---

This code was used to create the files found in the *data_raw* and *data_clean* repositories. No need to run this code if you downloaded the *Reproducible R Assigment* from GitHub. 

```{r eval= FALSE,echo=FALSE}

#set working directory using the following path: Session> Set working directory> Choose working directory
#select the location of the folder downloaded from GitHub (Reproducible R Assignment)

#install packages- only run the code corresponding to the packages that are not yet installed
install.packages("palmerpenguins") #contains the dataset
install.packages("ggplot2") #for plotting
suppressPackageStartupMessages(library(janitor)) #for cleaning up the dataset
suppressPackageStartupMessages(library(dplyr)) #for producing functions
install.packages("ragg") #for producing figures
install.packages("svglite") #for saving vectorised figures
```


```{r include= FALSE}
#load libraries 
source("functions/library_packages.R")

#load functions from repository
source("functions/cleaning.R")
source("functions/plotting.R")

```


```{r include=FALSE}
#view raw data and save a version of it 
penguins_raw
dir.create("data_raw")
write.csv(penguins_raw, "data_raw/penguins_raw.csv")
```


```{r include= FALSE}
#tidy data
penguins_clean <- cleaning(penguins_raw)
dir.create("data_clean")
write.csv(penguins_clean, "data_clean/penguins_clean.csv")
penguins_clean

#remove penguins that do not have information on culmen length and body mass, keep only the columns that contain relevant information for the analysis 
penguins_no_na<- remove_na(penguins_clean)
write.csv(penguins_no_na, "data_clean/penguins_no_na.csv")
penguins_no_na

#simplify penguin species names
penguins_simplified<-penguins_no_na
penguins_simplified$species<-word(penguins_no_na$species, 1)
penguins_simplified
write.csv(penguins_simplified, "data_clean/penguins_simplified.csv")

```